name: Minimal Cache Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p cache-folder && echo "Hello cache!" > cache-folder/file.txt

      - uses: actions/cache@v4
        id: cache
        with:
          path: cache-folder
          key: cache-85700f9

      - name: prime-cache-85700f9   # ✅ This is the required step name
        run: |
          echo "Cache hit status: ${{ steps.cache.outputs.cache-hit }}"
